### ISSUE TITLE
GUI - Expanding alert/event rows causes multiple API calls

### ISSUE THREAD

**Issue by automationator** [ace-ecosystem/ace2-ams#115]
When you expand a row on either the Manage Alerts or Manage Events table, it makes an API call to fetch the data about that alert/event.

However, when you already have a row expanded and expand a second row, instead of making an API call for only the newly expanded row, it makes two API calls - one for the previously expanded row, and one for the newly expanded row.

It should only need to make a single call.

**Comment by hollyfoxx** [comment]
Closed by #122

**Comment by hollyfoxx** [comment]
Closed by #122
